all:
  vars:
    ansible_user: admin

  hosts:
    k3s-master:
      ansible_host: 192.168.1.10
    k3s-worker:
      ansible_host: 192.168.1.11
    database:
      ansible_host: 192.168.1.100
    rancher:
      ansible_host: 192.168.1.200

  children:
    k3s_master:
      hosts:
        k3s-master:
          ansible_host: 192.168.1.10

    k3s_worker:
      hosts:
        k3s-worker:
          ansible_host: 192.168.1.11

    database:
      hosts:
        db-node:
          ansible_host: 192.168.1.100

    rancher:
      hosts:
        rancher-node:
          ansible_host: 192.168.1.200