- hosts: all
  become: yes
  roles:
    - common

- hosts: k3s_master
  become: yes
  roles:
    - k3s_server

- hosts: k3s_worker
  become: yes
  roles:
    - k3s_agent

- hosts: database
  become: yes
  roles:
    - database

- hosts: rancher
  become: yes
  roles:
    - rancher