name: Terraform CD

on:
  push:
    branches:
      - dev
    paths:
      - 'terraform/**'
      - 'ansible/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:        
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Clean Terraform
        run: |
          rm -rf .terraform
          rm -f .terraform.lock.hcl

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -upgrade

      - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
          TF_VAR_node: ${{ secrets.PM_NODE_NAME }}
          #TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}
          #TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible
        run: ansible-playbook -i ansible/inventories/dev/hosts.yml ansible/playbook.yml
